Repository Elena-Lou/Cub3D, pull requests merged in 2022-10, with the labels that each got.

#16 ADD .GITHOOKS:
  .githooks/pre-commit
  .githooks/pre-merge-commit
Labels: ADD

#17 ADD MOVES ROTATION 2D DISPLAY:
  Makefile
  include/cub3d.h
  srcs/image/key_checks.c
  srcs/image/minimap.c
  srcs/image/rendition.c
  srcs/main.c
  srcs/movement/player_movement.c
  srcs/movement/player_rotation.c
  srcs/parsing/check_map_grid.c
  srcs/parsing/create_map_grid.c
  srcs/raycasting/dda.c
Labels: ADD

#19 ADD MAP_HEIGHT AND MAP_WIDTH TO DATA STRUCT:
  include/cub3d.h
  srcs/main.c
  srcs/movement/player_movement.c
  srcs/parsing/check_map_content.c
Labels: ADD

#20 ADD DDA ALGO:
  Makefile
  include/cub3d.h
  maps/default.cub
  srcs/image/rendition.c
  srcs/raycasting/dda.c
  srcs/raycasting/dda_maths.c
  srcs/raycasting/dda_rays.c
Labels: ADD

#21 ADD DEFAULT MAPS WITH DIFFERENT ORIENTATION:
  maps/default_east.cub
  maps/default_north.cub
  maps/default_south.cub
  maps/default_west.cub
Labels: enhancement, ADD

#22 FIX SEGFAULT IN WRONG MAPS:
  Makefile
  srcs/main.c
Labels: FIX

#25 FIX ROTATION:
  include/cub3d.h
  srcs/image/rendition.c
  srcs/movement/key_checks.c
  srcs/movement/player_movement.c
  srcs/movement/update_tile.c
  srcs/parsing/check_map_grid.c
Labels: FIX

#29 ADD WALL PROJECTION FEATURE:
  Makefile
  include/cub3d.h
  maps/default_north.cub
  maps/kate_mousse.cub
  srcs/image/rendition.c
  srcs/main.c
  srcs/raycasting/dda.c
  srcs/raycasting/dda_maths.c
  srcs/raycasting/dda_rays.c
  srcs/raycasting/wall_projection.c
Labels: ADD

#31 FIX WALL PROJECTION CORNER WINDOWS:
  Makefile
  include/cub3d.h
  maps/small.cub
  srcs/main.c
  srcs/raycasting/dda_rays.c
  srcs/raycasting/wall_projection.c
Labels: FIX

#34 ADD TEXTURED WALLS && FIX USAGE MESSAGE:
  Makefile
  include/cub3d.h
  maps/small.cub
  srcs/image/rendition.c
  srcs/image/window_utils.c
  srcs/main.c
  srcs/raycasting/dda_maths.c
  srcs/raycasting/dda_rays.c
  srcs/raycasting/wall_projection.c
  srcs/textures/apply_textures.c
  srcs/textures/pick_colours.c
Labels: FIX, ADD

#35 UPDATE TEXTURE RENDERING:
  include/cub3d.h
  maps/small.cub
  srcs/image/rendition.c
  srcs/textures/apply_textures.c
  srcs/textures/pick_colours.c
Labels: enhancement, FIX

#39 FIX PARSING:
  Makefile
  include/cub3d.h
  maps/kate_mousse.cub
  srcs/image/minimap.c
  srcs/main.c
  srcs/parsing/check_ceilling_floor_texture_functions.c
  srcs/parsing/check_map_content.c
  srcs/parsing/check_map_grid.c
  srcs/parsing/check_tile.c
  srcs/parsing/check_wall_texture_functions.c
  srcs/parsing/map_to_list.c
  srcs/textures/set_textures.c
  srcs/utils/error_message.c
  srcs/utils/free_functions.c
Labels: FIX

#42 FIX MINIMAP AND PARSING:
  srcs/image/minimap.c
  srcs/parsing/check_map_grid.c
Labels: FIX

#45 UPDATE HEADER FILE:
  include/cub3d.h
  maps/multiple_players.cub
  maps/wrong_colours.cub
  maps/wrong_player.cub
  srcs/image/minimap.c
  srcs/image/window_utils.c
  srcs/image/window_utils_bonus.c
  srcs/main.c
  srcs/main_bonus.c
  srcs/movement/key_checks.c
  srcs/movement/key_checks_bonus.c
  srcs/parsing/check_ceilling_floor_texture_functions.c
  srcs/parsing/check_ceilling_floor_texture_functions_bonus.c
  srcs/parsing/check_map_content.c
  srcs/parsing/check_map_content_bonus.c
  srcs/parsing/check_map_grid.c
  srcs/parsing/check_map_grid_bonus.c
  srcs/parsing/check_newlines_bonus.c
  srcs/parsing/check_wall_texture_functions.c
  srcs/parsing/check_wall_texture_functions_bonus.c
  srcs/parsing/create_map_grid.c
  srcs/parsing/create_map_grid_bonus.c
  srcs/raycasting/dda_rays.c
  srcs/raycasting/dda_rays_bonus.c
  srcs/raycasting/wall_projection.c
  srcs/raycasting/wall_projection_bonus.c
Labels: enhancement

#49 ADD NEW MAPS:
  maps/map_before_textures.cub
  maps/no_grid.cub
  maps/oneline.cub
  maps/only_player.cub
  maps/small.cub
Labels: ADD

#51 FIX SEGFAULT OF DEATH IN INCORRECT MAPS:
  bonus/srcs/parsing/check_map_content_bonus.c
  bonus/srcs/parsing/create_map_grid_bonus.c
  mandatory/srcs/parsing/check_map_content.c
  mandatory/srcs/parsing/create_map_grid.c
  maps/no_no.cub
Labels: FIX
