Repository Elena-Lou/Cub3D, pull requests merged in 2022-09, with the labels that each got.

#1 Aw/fix makefile
  .gitignore
  Makefile
  maps/default.cub
  srcs/.syntastic_c_config
  srcs/parsing/map_check.c
Labels: enhancement

#7 ADD XPM FILES FOR WALLS TEXTURES:
  images/blue_wall.xpm
  images/brick.xpm
  images/brown_wall.xpm
  images/grey_wall.xpm
  images/red_brick.xpm
Labels: ADD

#8 FIX LEAKS && ADD TDD FOR WALLS:
  Makefile
  include/cub3d.h
  maps/default.cub
  srcs/main.c
  srcs/parsing/check_ceilling_floor_texture_functions.c
  srcs/parsing/check_wall_texture_functions.c
  srcs/parsing/map_to_list.c
  srcs/test/main_map_tester.c
  srcs/test/test_maps.sh
Labels: FIX, ADD

#10 ADD MAP GRID:
  Makefile
  include/cub3d.h
  srcs/main.c
  srcs/parsing/check_map_content.c
  srcs/parsing/check_map_grid.c
  srcs/parsing/check_wall_texture_functions.c
  srcs/parsing/map_to_list.c
  srcs/test/main_map_tester.c
  srcs/utils/free_functions.c
Labels: ADD
